<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Weekplan.Core.Rechnen\Weekplan.Core.Rechnen.csproj" />
    <ProjectReference Include="..\Weekplan.Core.Rechnen.Contracts\Weekplan.Core.Rechnen.Contracts.csproj" />
    <ProjectReference Include="..\Weekplan.Core.Anmeldung\Weekplan.Core.Anmeldung.csproj" />
    <ProjectReference Include="..\Weekplan.Core.Anmeldung.Contracts\Weekplan.Core.Anmeldung.Contracts.csproj" />
    <ProjectReference Include="..\Weekplan.Core.Tagebuch\Weekplan.Core.Tagebuch.csproj" />
    <ProjectReference Include="..\Weekplan.Core.Tagebuch.Contracts\Weekplan.Core.Tagebuch.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
